version: "3"

services:
  brat:
    image: "matcomuh/satr:latest"
    build:
      context: ./build
      dockerfile: brat.dockerfile
    container_name: "autobrat-brat"
    ports:
      - "8081:80"
    volumes:
      - "./data:/bratdata/SAT+R"

  autobrat:
    image: "matcomuh/autobrat:latest"
    build:
      context: ./build
      dockerfile: autobrat.dockerfile
    container_name: autobrat-web
    ports:
      - "8000:8000"
    volumes:
      - "./data/autobrat:/data"
      - "./autobrat:/code"
      - "./scripts:/usr/local/lib/python3.6/site-packages/scripts"
      - "./autobrat:/usr/local/lib/python3.6/site-packages/autobrat"
    working_dir: "/code"
    command: ["uvicorn", "--host", "0.0.0.0", "--reload", "--log-level", "debug", "app:app"]
